import { InjectionToken } from "@angular/core";
import { IAuthService } from "./interfaces";

const APP_WEB3AUTH_SERVICE_TOKEN = new InjectionToken<IAuthService>('APP_WEB3AUTH_SERVICE');
const APP_PINNING_SERVICE_DEFAULT_CONFIG_TOKEN = new InjectionToken('APP_PINNING_SERVICE_DEFAULT_CONFIG');

const TOKENS_MAP = new Map();
TOKENS_MAP.set('APP_WEB3AUTH_SERVICE', APP_WEB3AUTH_SERVICE_TOKEN);
TOKENS_MAP.set('APP_PINNING_SERVICE_DEFAULT_CONFIG', APP_PINNING_SERVICE_DEFAULT_CONFIG_TOKEN);

export enum TOKENS_NAME  {
  APP_WEB3AUTH_SERVICE = 'APP_WEB3AUTH_SERVICE',
  APP_PINNING_SERVICE_DEFAULT_CONFIG = 'APP_PINNING_SERVICE_DEFAULT_CONFIG'
}

export function getInjectionToken(tokenName: string) {
  return TOKENS_MAP.get(tokenName);
}
